services:
  db:
    image: postgres:15
    container_name: bitlab-db
    restart: always
    environment:
      POSTGRES_DB: bitlab_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  main-service:
    container_name: bitlab-main
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_DSN: host=db user=postgres password=postgres dbname=bitlab_lms port=5432 sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata:
