version: '3.8'

services:
  #########################################
  # 📦 PostgreSQL (App DB)
  #########################################
  app_db:
    image: postgres:15
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitlab_lms
    volumes:
      - app_db_data:/var/lib/postgresql/data
      - ./migrations/sql:/app/migrations/sql
    ports:
      - "5432:5432"

  #########################################
  # 🛡️ PostgreSQL for Keycloak
  #########################################
  keycloak_db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  #########################################
  # 🔑 Keycloak Identity Provider
  #########################################
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - keycloak_db
    volumes:
      - ./keycloak/init:/opt/keycloak/data/import

  #########################################
  # ☁️ MinIO (S3-compatible storage)
  #########################################
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
      - ./init-bucket.sh:/init-bucket.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 5

  #########################################
  # 🧠 Main Golang API Service
  #########################################
  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_service
    ports:
      - "8080:8080"
    depends_on:
      minio:
        condition: service_healthy
      app_db:
        condition: service_started
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
    env_file:
      - .env

volumes:
  minio_data:
  app_db_data:
  keycloak_db_data:
