version: '3.8'

services:
  app_db:
    image: postgres:15
    container_name: app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitlab_lms
    volumes:
      - app_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak_db:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # If you want to access Keycloak's DB from host for testing

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - keycloak_db

  main_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_service
    ports:
      - "8080:8080"
    depends_on:
      - app_db
    env_file:
      - .env
volumes:
  app_db_data:
  keycloak_db_data:
